Modelo place hecho
irkus1911/KedamosOdoo pull request #1
Opened 2021-12-15 11:57 UTC by UnaiUrti

Queridos compañeros, creo que he terminado el modelo place completamente. Si es posible os agradecería que echéis una ojeada al código y confirmar si está todo correcto. Un saludo.

2021-12-15 12:30 UTC, 19adrii28 requested changes
Querido compañero Unai, revisando tu codigo he caido en la cuenta que la relacion One2many la tienes mal escrita, linea 12

2021-12-15 12:35 UTC, 19adrii28 reviewed
Si miras sigues el modelo de datos mejor

2021-12-15 12:37 UTC, UnaiUrti commented
> 

Muchas gracias caballero ahora mismo lo cambio

2021-12-15 12:39 UTC, UnaiUrti commented
Corregido compañeros. Echadle un último vistazo por favor

2021-12-16 07:17 UTC, irkus1911 reviewed
Lo veo bien

2021-12-16 07:18 UTC, irkus1911 approved these changes

2021-12-16 07:27 UTC, 19adrii28 approved these changes
Todo bien

2021-12-16 07:39 UTC, UnaiUrti commented
Perfecto compañeros, ahora mismo voy a proceder a hacer el merge a la master. Un saludo.

2021-12-16 07:39 UTC, merged