Modelo personal_resource
irkus1911/KedamosOdoo pull request #2
Opened 2021-12-15 12:04 UTC by irkus1911

Mirar esto para confirmar que esta bien

2021-12-15 12:10 UTC, UnaiUrti requested changes
Querido compañero Irkus, disculpe que me inmiscuya, pero creo que has de eliminar el atributo 'id_personalResource' ya que como ha dicho nuestro profesorado la clase Model ya incluye un identificador. Un saludo.

2021-12-15 12:11 UTC, 19adrii28 requested changes
Además de lo de Unai, mira la linea 13, te falta una coma al finaall igual luego te casca o algo por eso 😬

2021-12-15 12:43 UTC, 19adrii28 reviewed
Irkus, yo he seguido el modelo de datos y en vez de event_id lo he llamado event a secas, ahora lo subo para que veas

2021-12-15 12:58 UTC, UnaiUrti approved these changes
Esta vez lo veo bien aunque la parte final de la enumeración no la termino de entender muy bien. Un saludo.

2021-12-16 07:22 UTC, 19adrii28 approved these changes
Ahora perfect 💯🙂

2021-12-16 07:38 UTC, merged